### ISSUE TITLE
Method not recognized if imported in AppModule

### ISSUE THREAD

**Issue by sasos90** [Jeff-Tian/grpc-health#2]
I am not sure what is the problem, but if I import the controller in the `AppModule`, then it doesn't work, but if I import it in e.g. `SearchModule` which is imported in the `AppModule` then it works.
It also doesn't work if I create a `HealthModule`, import the controller IN `HealthModule`, and import the `HealthModule` in `AppModule` (actually the same thing like with `SearchModule`). Does it have something with the package name? I have package name `search`, hence it works only in `SearchModule`?

Error:
`Method handler for ... expected but not provided`

**Comment by Jeff-Tian** [comment]
@sasos90 Thanks for your feedback! Could you please share your repo that can help reproduce the issue a little easier?

**Comment by sasos90** [comment]
Hey everything was ok! The problem was, I misslooked that AppModule was not the module that was used as a gRPC service, but SearchModule :)

Thanks!

**Comment by Jeff-Tian** [comment]
Good to know it works! Get in touch.
