### ISSUE TITLE
Update Nest Version

### ISSUE THREAD

**Issue by Monahawk** [Jeff-Tian/grpc-health#6]
Hey, I have some issues, since it seems you are not supporting the latest Nest version.
The GrpcOptions are different in Nest 6.1.xxx and Nest 7.x.x.
If it is not such a huge problem, could there be an update on your Nest Version?

**Comment by Jeff-Tian** [comment]
PR is welcome!

I'll have time to look into it next month if no one help update it.

**Comment by Jeff-Tian** [comment]
@Monahawk thanks for your feedback!

Now [v.1.4.0](https://www.npmjs.com/package/grpc-health/v/1.4.0) is ready for supporting latest Nest 7.4.4.  :-)
